In [1]:
!pip install numpy

In [2]:
import numpy as np

In [10]:
a=np.array([])
b=np.array([1,2,3,4,5,0])
c=np.array([[12,3,4],[34,2,4]])

In [6]:
a

array([], dtype=float64)

In [12]:
b

array([1, 2, 3, 4, 5, 0])

In [11]:
c

array([[12,  3,  4],
       [34,  2,  4]])

In [14]:
type(c)

numpy.ndarray

In [15]:
c.ndim

2

In [16]:
c.size

6

In [17]:
c.shape

(2, 3)

In [18]:
n = np.array([  [ 2,3,4,5 ] , [ 10,20,30,40 ] , [ 100,200,300,400 ]  ])

In [19]:
n.shape

(3, 4)

In [1]:
n = np.array([  [ 2,3,4,5 ] , [ 10,20,30,40 ] , [ 100,200,300,400 ]  ])

NameError: name 'np' is not defined

In [7]:
import numpy as np


In [8]:
n = np.array([  [ 2,3,4,5 ] , [ 10,20,30,40 ] , [ 100,200,300,400 ]  ])

In [9]:
n[0,0]

2

In [10]:
n

array([[  2,   3,   4,   5],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

## SYNTAX = n[row,col]

In [12]:
n[1:,2:]

array([[ 30,  40],
       [300, 400]])

In [13]:
n[1:3,2:4]

array([[ 30,  40],
       [300, 400]])

In [14]:
n[1:3,3]

array([ 40, 400])

In [15]:
n[0:3,3]

array([  5,  40, 400])

## arrange

(range(2,400))

list(range(2,400))

In [18]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

## reshape

In [26]:
a= np.arange(12).reshape(6,2)

In [23]:
np.sqrt(121)

11.0

In [27]:
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [28]:
a.max()

11

In [29]:
n.argmax()

11

In [30]:
n.argmin()

0

In [31]:
a*3

array([[ 0,  3],
       [ 6,  9],
       [12, 15],
       [18, 21],
       [24, 27],
       [30, 33]])

In [32]:
a-4

array([[-4, -3],
       [-2, -1],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

## Random

In [33]:
np.random.rand(2,2)

array([[0.97816394, 0.72346725],
       [0.64381937, 0.35936211]])

In [34]:
np.random.rand(2)

array([0.79910254, 0.3731885 ])

In [35]:
np.random.randn(2,2)

array([[ 0.38866834,  1.34582178],
       [-0.03421681, -1.93013482]])

In [39]:
s=np.random.randint(9,90,12).reshape(6,2)

s.sum()

In [40]:
s.sum()

583

In [42]:
s.sum(axis=1)

array([ 43,  97,  85, 159,  83, 116])

## 3D

In [45]:
r =np.array( [[[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,50],[4,40],[6,60]]])

In [46]:
r.shape

(3, 3, 2)

## Nan-not a number

In [48]:
x = np.array([12,56,np.nan,66,100,np.nan])

In [49]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [51]:
x.dtype

dtype('float64')

In [52]:
import pandas as pd